### ISSUE TITLE
Github organization: aphasia-apps

### ISSUE THREAD

**Issue by rbcavanaugh** [aphasia-apps/pnt#23]
Everyone - 

I would like to move the PNT repository from my personal github to a larger github organization I created called 'aphasia-apps'

The PNT app is one of several apps I've been collaborating on, there are a few related to discourse assessment. I know there are some tentative plans to create an ACOM app as well (though it doesn't necessarily need to be under the organization). I imagine there will be more in the future. 

The goal of the organization would be to have a central location for anyone to host code for shiny-apps for aphasia in the future. The structure allows many members, who can have different access to different repositories under the organization (e.g. Alex/Will/G have access to the PNT repository, but not a different repository they're not involved in). It would also allow clinicians/researchers to browse aphasia-oriented shiny apps all in one place. Plus, it's free, code remains open source, and accessible to anyone. 

An ideal (optimistic) long-term outcome is that our work using shiny will spur even more types of assessments or aphasia/related disorders resources being implemented in the shiny framework (or the corresponding python framework, Dash), and made free and easy for clinicians to access. By creating a central organization, it also creates a venue for newcomers to shiny or anyone creating aphasia-oriented shiny apps to ask for help or suggestions with their own ideas/plans. 

Finally, it would allow the use of URLs for the apps that are not associated with my github username, but is more memorable/general to aphasia. The repository would be located at https://github.com/aphasia-apps/PNT for example. If a repository website is created for documentation purposes (this is a free feature github offers), it would be hosted at https://aphasia-apps.github.io/PNT/. (this does not affect the location of the shiny app itself, which has to be hosted through shinyapps.io or a dedicated server). 

You won't notice any change from what the app is currently, other than a URL change and that there is a broader organization. 

Please let me know what you think of this idea, or if you have any questions. If everyone is on board, I'll transfer the repository to the organization and set up permissions.

**Comment by william-hula** [comment]
This works for me.

From: Rob Cavanaugh ***@***.***>
Sent: Friday, July 30, 2021 9:28 PM
To: rbcavanaugh/pnt ***@***.***>
Cc: Hula, William D ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [rbcavanaugh/pnt] Github organization: aphasia-apps (#23)


Everyone -

I would like to move the PNT repository from my personal github to a larger github organization I created called 'aphasia-apps'

The PNT app is one of several apps I've been collaborating on, there are a few related to discourse assessment. I know there are some tentative plans to create an ACOM app as well (though it doesn't necessarily need to be under the organization). I imagine there will be more in the future.

The goal of the organization would be to have a central location for anyone to host code for shiny-apps for aphasia in the future. The structure allows many members, who can have different access to different repositories under the organization (e.g. Alex/Will/G have access to the PNT repository, but not a different repository they're not involved in). It would also allow clinicians/researchers to browse aphasia-oriented shiny apps all in one place. Plus, it's free, code remains open source, and accessible to anyone.

An idea long-term outcome is that our work using shiny will spur even more types of assessments or aphasia/related disorders resources being implemented in the shiny framework (or the corresponding python framework, Dash), and made free and easy for clinicians to access. By creating a central organization, it also creates a venue for newcomers to shiny or anyone creating aphasia-oriented shiny apps to ask for help or suggestions with their own ideas/plans.

Finally, it would allow the use of URLs for the apps that are not associated with my github username, but is more memorable/general to aphasia. The repository would be located at https://github.com/aphasia-apps/PNT<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faphasia-apps%2FPNT&data=04%7C01%7C%7C310279141a92465bb2d108d953c26661%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637632916687471019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g%2Fe9wjhsS5aKXyHbiMteOaQFnCfsvj4ap5gRoyK%2FLms%3D&reserved=0> for example. If a repository website is created for documentation purposes (this is a free feature github offers), it would be hosted at https://aphasia-apps.github.io/PNT/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faphasia-apps.github.io%2FPNT%2F&data=04%7C01%7C%7C310279141a92465bb2d108d953c26661%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637632916687480977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=H9zX17EhtI3pJVS2pESMU72YJd58OcIkBG6zpuQlEfM%3D&reserved=0>. (this does not affect the location of the shiny app itself, which has to be hosted through shinyapps.io or a dedicated server).

Please let me know what you think of this idea, or if you have any questions. If everyone is on board, I'll transfer the repository to the organization and set up permissions.

-

**Comment by rbcavanaugh** [comment]
moved!
