### ISSUE TITLE
Incorrect shading on density plot on results summary page

### ISSUE THREAD

**Issue by william-hula** [aphasia-apps/pnt#37]
Getting back into this project to run a simulation study to select a final scoring algorithm (MLEF vs. EAP), and I noticed that the lower bound of the shaded area in the density plot on the results summary doesn't correspond to the lower bound of the CI, but the upper one does.
![image](https://user-images.githubusercontent.com/87673084/173254328-a4965d8a-8f9a-4407-974d-acaa743fdeec.png)

**Comment by rbcavanaugh** [comment]
Good catch. Looks like the shaded area refuses to go lower than 20 (and higher than 80). It's a relatively trivial fix - though it did make me realize that the 335 T-scores that go into the density plot range from ~22 to ~71. The density plot smooths the tails which I think is probably good for visualization but I'm not sure if that's a concern. Perhaps this will be addressed in part by the fencing?
