### ISSUE TITLE
Formalize results text

### ISSUE THREAD

**Issue by rbcavanaugh** [aphasia-apps/pnt#4]
Results text should do 3 things: 

- summarize the results in a format that could be copied into a clinicians notes
- describe the ability estimate in practical terms, such as the probability of a correct response for a few key items
- add the crosswalk estimate for the number of items likely to be produced correctly on the full PNT

**Comment by william-hula** [comment]
Agree, except, that's 3 things. The crosswalk to the full PNT could or should include an interval estimate based on the score CI.

**Comment by AlexSwiderski** [comment]
> Agree, except, that's 3 things. The crosswalk to the full PNT could or should include an interval estimate based on the score CI.

math...
