### ISSUE TITLE
App needs a set of clear instructions with a very brief primer on IRT

### ISSUE THREAD

**Issue by rbcavanaugh** [aphasia-apps/pnt#7]
- primer on IRT (with pointer to Alex's app/site)
- short summary of IRT research and anomia...what the app will tell you and what it wont
- how to use app, including current functionality (see Jupyter notebook)
- how to report a bug, provide feedback
- pointer to instructions for forking/cloning repo for researchers (recommendation is to *NOT* use the web based version)

there is a preliminary version from AS in the www/ folder called info.RMD ##NEEDS UPDATING, AS has on person computer

**Comment by AlexSwiderski** [comment]
Providing instructions to undergrads on 7/7/21.  I will request they return comments by 7/12.

**Comment by rbcavanaugh** [comment]
ok I will try to fix the upload data error we ran into the last meeting n the morning. You might add one last request #9 which is for them to take 10 minutes and see if they can use the app in a way that wasn't in the instructions. some kind of 'free use' would be good too

**Comment by AlexSwiderski** [comment]
Great idea

**Comment by gfergadiotis** [comment]
Let me know if you would like me to ask the two SLPs in my lab to "break" the app.

**Comment by rbcavanaugh** [comment]
We should definitely do this after we get feedback from the students at VA Pittsburgh

**Comment by AlexSwiderski** [comment]
I have the information from Lexi and Pauline, was waiting to share at a meeting.  I will shoot it out in an email later today.

**Comment by rbcavanaugh** [comment]
Adding to this thread, that we should spend 5 minutes talking about the flow from when the site is opened to the end. It seems to me like a very simple intro page with a "get started" button would be better than asking for information right off the bat.

**Comment by rbcavanaugh** [comment]
make the following change to the intro_tab:

page 1: Short introduction
page 2: instructions (what to press to enter results/advance page)
page 3: enter name/date

**Comment by rbcavanaugh** [comment]
lots of places - clarify what keys mean what

- [ ] repeat instructions page at end of practice items
- [ ]  alert when hitting i key for more ingo
- [ ] score notification (no response recorded) to include potential resposnes

**Comment by rbcavanaugh** [comment]
closing this as W.H. has provided a lot of content. needs to be edited only
